CREATE DATABASE LIBROS_REGISTROS;

USE DATABASE LIBROS_REGISTROS;

CREATE TABLE EDITORIAL (
    ID_EDITORIAL INT PRIMARY KEY AUTO_INCREMENT,
    EDITORIAL VARCHAR(100) NOT NULL
);
CREATE TABLE CATEGORIA (
    ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    CATEGORIA VARCHAR(100) NOT NULL
);

CREATE TABLE LIBRO (
    ID_LIBRO INT PRIMARY KEY AUTO_INCREMENT,
    ISBN VARCHAR(20) NOT NULL UNIQUE,
    TITULO VARCHAR(200) NOT NULL,
    AUTOR VARCHAR(100) NOT NULL,
    ID_EDITORIAL INT,
    ID_CATEGORIA INT,
    FECHA_PUBLICACION DATE,
    PRECIO DECIMAL(10,2),
    STOCK INT,
    FOREIGN KEY (ID_EDITORIAL) REFERENCES EDITORIAL(ID_EDITORIAL),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE PEDIDO (
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    ID_LIBRO INT,
    ID_CLIENTE INT,
    ID_METODO_PAGO INT,
    MONTO DECIMAL(10,2),
    FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO(ID_LIBRO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_METODO_PAGO) REFERENCES METODO_PAGO(ID_METODO_PAGO)
);
CREATE TABLE CLIENTE (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    CORREO VARCHAR(100) NOT NULL UNIQUE,
    TELEFONO VARCHAR(15),
    DIRECCION VARCHAR(200)
);
CREATE TABLE METODO_PAGO (
    ID_METODO_PAGO INT PRIMARY KEY AUTO_INCREMENT,
    METODO_PAGO VARCHAR(50) NOT NULL
);